INSERT INTO APP.USERS (NAME, ONLINE) VALUES ('Yura', 1);
INSERT INTO APP.USERS (NAME, ONLINE) VALUES ('Pasha', 0);
INSERT INTO APP.USERS (NAME, ONLINE) VALUES ('Tanya', 1);
INSERT INTO APP.MESSAGES (MESSAGE, USER_ID) VALUES ('Hello world!',1);
INSERT INTO APP.MESSAGES (MESSAGE, USER_ID) VALUES ('test message',1);
INSERT INTO APP.MESSAGES (MESSAGE, USER_ID) VALUES ('another test message',1);